name: Build & Test C++ CMake Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:  # Enables Workflow to Run Manually

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Check installed Visual Studio versions
      run: |
        Get-Command -Name devenv -ErrorAction SilentlyContinue
        Get-Command -Name msbuild -ErrorAction SilentlyContinue

    - name: Set up Visual Studio
      run: |
        choco install visualstudio2019community
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
        RefreshEnv

    - name: Configure
      run: cmake -Bbuild -DCMAKE_MAKE_PROGRAM='C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe'

    - name: Build
      run: cmake --build build --config Release

    - name: Run CI Tests
      run: |
        cd out
        cd build
        cd x64-debug
        cd Unittest
        ./Unittest.exe
