name: Build & Test C++ CMake Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:  # Enables Workflow to Run Manually

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up CMake
      uses: jwlawson/actions-setup-cmake@v1.14.1
      with:
        cmake-version: '3.16.x'

    - name: Configure
      run: cmake -Bbuild -G "Visual Studio 16 2019" -A x64

    - name: Build
      run: cmake --build build --config Release

    - name: Run CI Tests
      run: |
        cd out
        cd build
        cd x64-debug
        cd Unittest
        ./Unittest.exe
